name: Generate Trophies

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate trophy card
        uses: soulteary/github-profile-trophy-action@v1
        with:
          username: DonBos27
          theme: radical
          row: 2
          column: 4
          margin_w: 15
          margin_h: 15
          no_bg: true
          output_dir: ./dist

      - name: Publish trophy files to output branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output